app = "wp-docker"
primary_region = "gru"

[build]

[env]
WORDPRESS_DB_NAME = "sql3786429"
WORDPRESS_DB_USER = "sql3786429"
WORDPRESS_DB_PASSWORD = "JSvZY4jVwM"
WORDPRESS_DB_HOST = "sql3.freesqldatabase.com"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
